# Generated by Django 2.2.3 on 2019-07-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('users', '0005_profile_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='post',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_post',
            field=models.ManyToManyField(to='blog.Post'),
        ),
    ]
