# Generated by Django 2.2.3 on 2019-07-28 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190729_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_post',
        ),
    ]
