# Generated by Django 2.2.3 on 2019-07-28 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
    ]
